#nullable enable
namespace LiteDB.AotSmokeTests
{
    internal static partial class ExpressionSweepScenarios
    {
        // Key: METHOD_NAME~parameter count (without the implicit Collation), the same key LiteDB registers.
        // Values that depend on the clock, randomness, or the machine's time zone are reduced to a stable fact.
        private static readonly (string Key, string Expression)[] Methods =
        {
            // aggregates and enumerables
            ("COUNT~1", "COUNT($.items[*])"),
            ("MIN~1", "MIN($.items[*])"),
            ("MAX~1", "MAX($.items[*])"),
            ("FIRST~1", "FIRST($.items[*])"),
            ("LAST~1", "LAST($.items[*])"),
            ("AVG~1", "AVG($.items[*])"),
            ("SUM~1", "SUM($.items[*])"),
            ("ANY~1", "ANY($.items[*])"),
            ("ARRAY~1", "ARRAY($.items[*])"),
            ("ITEMS~1", "ARRAY(ITEMS($.tags))"),
            ("CONCAT~2", "ARRAY(CONCAT($.items[*], $.tags[*]))"),
            ("UNION~2", "ARRAY(UNION($.items[*], ITEMS([9, 1])))"),
            ("EXCEPT~2", "ARRAY(EXCEPT($.items[*], ITEMS([3])))"),
            ("DISTINCT~1", "ARRAY(DISTINCT($.items[*]))"),
            ("TOP~2", "ARRAY(TOP($.items[*], 2))"),
            ("JOIN~1", "JOIN($.tags[*])"),
            ("JOIN~2", "JOIN($.tags[*], '-')"),
            ("KEYS~1", "ARRAY(KEYS($.nested))"),
            ("VALUES~1", "ARRAY(VALUES($.nested))"),
            ("CONTAINSKEY~2", "CONTAINSKEY($.nested, 'x')"),

            // data type conversion
            ("MINVALUE~0", "IS_MINVALUE(MINVALUE())"),
            ("MAXVALUE~0", "IS_MAXVALUE(MAXVALUE())"),
            ("OBJECTID~0", "IS_OBJECTID(OBJECTID())"),
            ("OBJECTID~1", "OBJECTID('507f1f77bcf86cd799439011')"),
            ("GUID~0", "LENGTH(STRING(GUID()))"),
            ("GUID~1", "GUID('d29368bb-0d4c-4b8c-9d52-3f6c2a8e1b11')"),
            ("INT~1", "INT('42')"),
            ("INT32~1", "INT32(42.9)"),
            ("INT64~1", "INT64('5000000000')"),
            ("LONG~1", "LONG(42)"),
            ("DOUBLE~1", "DOUBLE('1.5')"),
            ("DOUBLE~2", "DOUBLE('1,5', 'de-DE')"),
            ("DECIMAL~1", "DECIMAL('19.99')"),
            ("DECIMAL~2", "DECIMAL('19,99', 'de-DE')"),
            ("STRING~1", "STRING($.age)"),
            ("BINARY~1", "BINARY('AQID')"),
            ("BOOL~1", "BOOL('true')"),
            ("BOOLEAN~1", "BOOLEAN('false')"),
            ("JSON~1", "JSON('{\"a\": [1, 2], \"b\": null}')"),
            ("EXTEND~2", "EXTEND($.nested, { z: 3 })"),
            ("COALESCE~2", "COALESCE($.nothing, 'fallback')"),
            ("IIF~3", "IIF($.age > 30, 'senior', 'junior')"),
            ("LENGTH~1", "[LENGTH($.name), LENGTH($.items), LENGTH($.nested), LENGTH($.bin)]"),
            ("IS_MINVALUE~1", "IS_MINVALUE($.age)"),
            ("IS_MAXVALUE~1", "IS_MAXVALUE($.age)"),
            ("IS_NULL~1", "IS_NULL($.nothing)"),
            ("IS_INT~1", "IS_INT($.age)"),
            ("IS_INT32~1", "IS_INT32($.age)"),
            ("IS_INT64~1", "IS_INT64($.big)"),
            ("IS_LONG~1", "IS_LONG($.big)"),
            ("IS_DOUBLE~1", "IS_DOUBLE($.score)"),
            ("IS_DECIMAL~1", "IS_DECIMAL($.price)"),
            ("IS_NUMBER~1", "IS_NUMBER($.price)"),
            ("IS_STRING~1", "IS_STRING($.name)"),
            ("IS_DOCUMENT~1", "IS_DOCUMENT($.nested)"),
            ("IS_ARRAY~1", "IS_ARRAY($.items)"),
            ("IS_BINARY~1", "IS_BINARY($.bin)"),
            ("IS_OBJECTID~1", "IS_OBJECTID($.oid)"),
            ("IS_GUID~1", "IS_GUID($.guid)"),
            ("IS_BOOL~1", "IS_BOOL($.flag)"),
            ("IS_BOOLEAN~1", "IS_BOOLEAN($.flag)"),
            ("IS_DATE~1", "IS_DATE($.born)"),
            ("IS_DATETIME~1", "IS_DATETIME($.born)"),

            // dates
            ("DATETIME~1", "YEAR(DATETIME('2020-05-06T07:08:09'))"),
            ("DATETIME~2", "MONTH(DATETIME('06.05.2020', 'de-DE'))"),
            ("DATETIME~3", "DATETIME(2020, 5, 6) = DATETIME(2020, 5, 6)"),
            ("DATETIME_UTC~1", "YEAR(DATETIME_UTC('2020-05-06T07:08:09Z'))"),
            ("DATETIME_UTC~2", "MONTH(DATETIME_UTC('06.05.2020', 'de-DE'))"),
            ("DATETIME_UTC~3", "DAY(DATETIME_UTC(2020, 5, 6))"),
            ("DATE~1", "YEAR(DATE('2020-05-06'))"),
            ("DATE~2", "MONTH(DATE('06.05.2020', 'de-DE'))"),
            ("DATE~3", "DAY(DATE(2020, 5, 6))"),
            ("DATE_UTC~1", "YEAR(DATE_UTC('2020-05-06'))"),
            ("DATE_UTC~2", "MONTH(DATE_UTC('06.05.2020', 'de-DE'))"),
            ("DATE_UTC~3", "DAY(DATE_UTC(2020, 5, 6))"),
            ("NOW~0", "IS_DATE(NOW())"),
            ("NOW_UTC~0", "IS_DATE(NOW_UTC())"),
            ("TODAY~0", "IS_DATE(TODAY())"),
            ("YEAR~1", "YEAR($.born)"),
            ("MONTH~1", "MONTH($.born)"),
            ("DAY~1", "DAY($.born)"),
            ("HOUR~1", "HOUR(DATETIME_UTC(2020, 5, 6)) >= 0"),
            ("MINUTE~1", "MINUTE(DATETIME_UTC(2020, 5, 6)) >= 0"),
            ("SECOND~1", "SECOND(DATETIME_UTC(2020, 5, 6))"),
            ("DATEADD~3", "YEAR(DATEADD('year', 5, $.born))"),
            ("DATEDIFF~3", "DATEDIFF('day', DATETIME_UTC(2020, 1, 1), DATETIME_UTC(2020, 1, 31))"),
            ("TO_LOCAL~1", "IS_DATE(TO_LOCAL($.born))"),
            ("TO_UTC~1", "IS_DATE(TO_UTC($.born))"),
            ("OID_CREATIONTIME~1", "YEAR(OID_CREATIONTIME($.oid))"),

            // math
            ("ABS~1", "ABS(-5)"),
            ("ROUND~2", "ROUND(12.3456, 2)"),
            ("POW~2", "POW(2, 10)"),
            ("RANDOM~0", "RANDOM() >= 0"),
            ("RANDOM~2", "RANDOM(5, 10) BETWEEN 5 AND 10"),

            // strings
            ("LOWER~1", "LOWER($.name)"),
            ("UPPER~1", "UPPER($.name)"),
            ("LTRIM~1", "LTRIM($.name)"),
            ("RTRIM~1", "RTRIM($.name)"),
            ("TRIM~1", "TRIM($.name)"),
            ("INDEXOF~2", "INDEXOF($.name, 'Love')"),
            ("INDEXOF~3", "INDEXOF($.name, 'a', 5)"),
            ("SUBSTRING~2", "SUBSTRING($.name, 6)"),
            ("SUBSTRING~3", "SUBSTRING($.name, 2, 3)"),
            ("REPLACE~3", "REPLACE($.name, 'Ada', 'Augusta')"),
            ("LPAD~3", "LPAD('7', 3, '0')"),
            ("RPAD~3", "RPAD('7', 3, '0')"),
            ("SPLIT~2", "ARRAY(SPLIT('a,b,c', ','))"),
            ("SPLIT~3", "ARRAY(SPLIT('a1b22c', '\\\\d+', true))"),
            ("FORMAT~2", "FORMAT($.age, '000')"),
            ("IS_MATCH~2", "IS_MATCH('abc123', '^[a-z]+\\\\d+$')"),
            ("MATCH~3", "MATCH('abc123', '([a-z]+)(\\\\d+)', 2)"),
            ("STRING_EQUALS~3", "STRING_EQUALS('Ada', 'ada', 'OrdinalIgnoreCase')"),
            ("STRING_EQUALS_INSTANCE~3", "STRING_EQUALS_INSTANCE('Ada', 'ada', 'OrdinalIgnoreCase')"),
            ("STRING_STARTSWITH~3", "STRING_STARTSWITH('Ada', 'a', 'OrdinalIgnoreCase')"),
            ("STRING_ENDSWITH~3", "STRING_ENDSWITH('Ada', 'A', 'OrdinalIgnoreCase')"),
            ("STRING_CONTAINS~3", "STRING_CONTAINS('Ada', 'D', 'OrdinalIgnoreCase')"),
            ("STRING_INDEXOF~3", "STRING_INDEXOF('Ada Lovelace', 'LOVE', 'OrdinalIgnoreCase')"),
            ("STRING_INDEXOF~4", "STRING_INDEXOF('Ada Lovelace', 'A', 1, 'OrdinalIgnoreCase')"),
            ("STRING_INDEXOF~5", "STRING_INDEXOF('Ada Lovelace', 'A', 1, 5, 'OrdinalIgnoreCase')"),

            // vectors
            ("VECTOR_SIM~2", "VECTOR_SIM($.vec, [1.0, 0.0])")
        };

        // Key: FUNCTION_NAME~number of arguments after the source and the mapping expression.
        private static readonly (string Key, string Expression)[] Functions =
        {
            ("MAP~0", "ARRAY(MAP($.items[*] => @ * 2))"),
            ("FILTER~0", "ARRAY(FILTER($.items[*] => @ > 1))"),
            ("SORT~0", "ARRAY(SORT($.items[*] => @))"),
            ("SORT~1", "ARRAY(SORT($.items[*] => @, -1))"),
            ("VECTOR_SIM~0", "$.vec VECTOR_SIM [0.0, 1.0]")
        };

        // Key: the operator method in BsonExpressionOperators, or the path form being exercised.
        private static readonly (string Key, string Expression)[] Operators =
        {
            ("ADD", "[1 + 2, 'a' + 'b', $.score + 0.5]"),
            ("MINUS", "$.age - 6"),
            ("MULTIPLY", "$.age * 2"),
            ("DIVIDE", "$.age / 8"),
            ("MOD", "$.age % 5"),
            ("EQ", "$.age = 36"),
            ("NEQ", "$.age != 36"),
            ("GT", "$.age > 35"),
            ("GTE", "$.age >= 36"),
            ("LT", "$.age < 36"),
            ("LTE", "$.age <= 36"),
            ("EQ_ANY", "$.items[*] ANY = 2"),
            ("EQ_ALL", "$.items[*] ALL = 3"),
            ("NEQ_ANY", "$.items[*] ANY != 3"),
            ("NEQ_ALL", "$.items[*] ALL != 9"),
            ("GT_ANY", "$.items[*] ANY > 2"),
            ("GT_ALL", "$.items[*] ALL > 0"),
            ("GTE_ANY", "$.items[*] ANY >= 3"),
            ("GTE_ALL", "$.items[*] ALL >= 2"),
            ("LT_ANY", "$.items[*] ANY < 2"),
            ("LT_ALL", "$.items[*] ALL < 4"),
            ("LTE_ANY", "$.items[*] ANY <= 1"),
            ("LTE_ALL", "$.items[*] ALL <= 2"),
            ("LIKE", "$.name LIKE '%Lovelace%'"),
            ("LIKE_ANY", "$.tags[*] ANY LIKE 'al%'"),
            ("LIKE_ALL", "$.tags[*] ALL LIKE '%a'"),
            ("BETWEEN", "$.age BETWEEN 30 AND 40"),
            ("BETWEEN_ANY", "$.items[*] ANY BETWEEN 0 AND 1"),
            ("BETWEEN_ALL", "$.items[*] ALL BETWEEN 1 AND 3"),
            ("IN", "$.age IN [35, 36]"),
            ("IN_ANY", "$.items[*] ANY IN [2, 9]"),
            ("IN_ALL", "$.items[*] ALL IN [1, 2]"),
            ("ARRAY_INDEX", "[$.items[0], $.items[-1]]"),
            ("ARRAY_FILTER", "ARRAY($.items[@ > 1])"),
            ("ARRAY_INIT", "[$.age, $.nested.x, 'literal']"),
            ("DOCUMENT_INIT", "{ age: $.age, twice: $.age * 2, inner: { y: $.nested.y } }"),
            ("MEMBER_PATH", "[$.nested.y, $.['name'], $.missing]"),
            ("PARAMETER_PATH", "[@0, @limit, $.age = @0]"),
            ("VECTOR_SIM", "$.vec VECTOR_SIM [1.0, 0.0]"),
            ("AND_OR", "[$.age > 30 AND $.flag = true, $.age > 40 OR $.flag = true]"),
            ("ROOT_AND_CURRENT", "ARRAY(MAP($.items[*] => @ + $.age))")
        };
    }
}
