"""Render the "Proven obligations" table of docs/rules/implement-safely.md from the net-proof ledger.

The implement-safely procedure makes an obligation mandatory only when its net has a
recorded proof (or the obligation is pure bookkeeping). This script turns
.github/safety/net-proofs.json into that table, one row per proof entry (harness
self-checks excluded): ledger rows, net, level (generic | reproduction), independence
(designed | tuned: the net was changed after reading the fix), the recorded result and
the assertion that fired. An entry without `results` (a skeleton) renders as
"not attempted"; only `proven` is a pass.

  --write FILE   replace the generated block between the BEGIN/END markers in FILE
  --check FILE   exit 1 when FILE's block differs from the ledger (stale table)
  (neither)      print the block
"""
import argparse
import re
import sys
from pathlib import Path

import safety_common as common

LEDGER = f"{common.SAFETY_DIR}/net-proofs.json"
BEGIN = "<!-- BEGIN proven-obligations: generated by .github/scripts/render_net_proofs.py; do not edit by hand -->"
END = "<!-- END proven-obligations -->"
BLOCK = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)


def independence(text):
    text = str(text or "")
    return "tuned" if text.startswith("tuned-after-fix") else "designed" if text else "?"


def _cell(text, limit=90):
    text = " ".join(str(text or "").split()).replace("|", "/")
    return text if len(text) <= limit else text[:limit - 1] + "…"


def rows(ledger, source=f"`{LEDGER}`"):
    entries = [entry for entry in ledger.get("proofs", [])
               if isinstance(entry, dict) and entry.get("level") != "harness-smoke"]
    entries.sort(key=lambda entry: (min(entry.get("rows") or [999]), str(entry.get("id"))))
    lines = ["| Rows | Net | Level | Independence | Result | Assertion at known-bad | Proof |",
             "| --- | --- | --- | --- | --- | --- | --- |"]
    for entry in entries:
        results = entry.get("results") or {}
        state = results.get("state", "not attempted")
        assertion = (results.get("knownBad") or {}).get("assertion") or "-"
        lines.append(f"| {', '.join(str(row) for row in entry.get('rows') or []) or '-'} "
                     f"| {_cell((entry.get('net') or {}).get('name'), 40)} | {entry.get('level', '?')} "
                     f"| {independence(entry.get('independence'))} | **{state}** | {_cell(assertion)} "
                     f"| `{entry.get('id')}` |")
    proven = sum(1 for entry in entries if (entry.get("results") or {}).get("state") == "proven")
    lines.append("")
    lines.append(f"{proven} of {len(entries)} entries proven. Rendered from {source}; refresh with "
                 "`python .github/scripts/render_net_proofs.py --write docs/rules/implement-safely.md`.")
    return lines


def render(ledger, source=f"`{LEDGER}`"):
    return "\n".join([BEGIN] + rows(ledger, source) + [END])


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--ledger", help=f"Ledger file (default: {LEDGER} in the working tree)")
    parser.add_argument("--source", help="How the footer names the ledger (default: its path)")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--write", help="Replace the generated block in this file")
    group.add_argument("--check", help="Fail when this file's generated block is stale")
    args = parser.parse_args(argv)
    path = Path(args.ledger) if args.ledger else Path(common.repo_root()) / LEDGER
    block = render(common.load_json_file(path), args.source or f"`{args.ledger or LEDGER}`")
    target = args.write or args.check
    if not target:
        print(block)
        return 0
    text = Path(target).read_text(encoding="utf-8")
    if not BLOCK.search(text):
        print(f"ERROR: {target} has no '{BEGIN}' ... '{END}' block")
        return 1
    updated = BLOCK.sub(lambda _: block, text, count=1)
    if args.check:
        if updated != text:
            print(f"ERROR: the proven-obligations table in {target} is stale; run render_net_proofs.py --write {target}")
            return 1
        print(f"{target}: proven-obligations table is current")
        return 0
    Path(target).write_text(updated, encoding="utf-8")
    print(f"Wrote the proven-obligations table to {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
