"""Render generated tables of the net-proof ledger into documentation.

The implement-safely procedure makes an obligation mandatory only when its net has a
recorded proof (or the obligation is pure bookkeeping). This script turns
.github/safety/net-proofs.json into that "Proven obligations" table of
docs/rules/implement-safely.md, one row per proof entry (harness self-checks excluded):
ledger rows, net, level (generic | reproduction | model | tuned-after-fix), independence
(designed | tuned: the net was changed after reading the fix), the recorded result and the
assertion that fired. An entry without `results` (a skeleton) renders as "not attempted";
only `proven` is a pass.

The same ledger also renders the blocks of docs/safety-net-retrospective.md:
verification-matrix (one line per defect row of the `defects` table), net-firings (per
net family: rows proven generically, by reproduction, tuned or on a model, fired
differently, not fired) and net-entries (every entry with class, result and time to
yell). A file may hold any of the blocks; each sits between its BEGIN/END markers.

  --write FILE   replace every generated block found in FILE
  --check FILE   exit 1 when a block in FILE differs from the ledger (stale table)
  (neither)      print the proven-obligations block
"""
import argparse
import re
import sys
from pathlib import Path

import safety_common as common

LEDGER = f"{common.SAFETY_DIR}/net-proofs.json"


def begin(name):
    return f"<!-- BEGIN {name}: generated by .github/scripts/render_net_proofs.py; do not edit by hand -->"


def end(name):
    return f"<!-- END {name} -->"


BEGIN, END = begin("proven-obligations"), end("proven-obligations")
BLOCK = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
REFRESH = "refresh with `python .github/scripts/render_net_proofs.py --write <file>`"
# What counts as a firing for a defect row, strongest first.
EVIDENCE = (("generic", "generic"), ("model", "model"), ("reproduction", "reproduction"),
            ("tuned-after-fix", "tuned"))


def independence(text):
    text = str(text or "")
    return "tuned" if text.startswith("tuned-after-fix") else "designed" if text else "?"


def _cell(text, limit=90):
    text = " ".join(str(text or "").split()).replace("|", "/")
    return text if len(text) <= limit else text[:limit - 1] + "…"


def _entries(ledger):
    return [entry for entry in ledger.get("proofs", [])
            if isinstance(entry, dict) and entry.get("level") != "harness-smoke"]


def _state(entry):
    return (entry.get("results") or {}).get("state", "not attempted")


def _family(entry):
    net = entry.get("net") or {}
    return str(net.get("family") or net.get("name") or "?")


def _rows_text(entry):
    return ", ".join(str(row) for row in entry.get("rows") or []) or "-"


def rows(ledger, source=f"`{LEDGER}`"):
    """Every entry that is not a plain not-fired one; the not-fired entries are counted per net family."""
    entries = _entries(ledger)
    entries.sort(key=lambda entry: (min(entry.get("rows") or [999]), str(entry.get("id"))))
    lines = ["| Rows | Net | Level | Independence | Result | Assertion at known-bad | Proof |",
             "| --- | --- | --- | --- | --- | --- | --- |"]
    quiet = {}
    for entry in entries:
        if _state(entry) == "not-fired":
            quiet[_family(entry)] = quiet.get(_family(entry), 0) + 1
            continue
        assertion = ((entry.get("results") or {}).get("knownBad") or {}).get("assertion") or "-"
        lines.append(f"| {_rows_text(entry)} "
                     f"| {_cell((entry.get('net') or {}).get('name'), 40)} | {entry.get('level', '?')} "
                     f"| {independence(entry.get('independence'))} | **{_state(entry)}** | {_cell(assertion)} "
                     f"| `{entry.get('id')}` |")
    proven = sum(1 for entry in entries if _state(entry) == "proven")
    lines.append("")
    if quiet:
        lines.append(f"Not fired ({sum(quiet.values())} entries, listed in the full matrix of "
                     "docs/safety-net-retrospective.md): "
                     + ", ".join(f"{name} {count}" for name, count in sorted(quiet.items(), key=lambda item: -item[1]))
                     + ".")
        lines.append("")
    lines.append(f"{proven} of {len(entries)} entries proven. Rendered from {source}; refresh with "
                 "`python .github/scripts/render_net_proofs.py --write docs/rules/implement-safely.md`.")
    return lines


def _by_row(ledger):
    grouped = {}
    for entry in _entries(ledger):
        for row in entry.get("rows") or []:
            grouped.setdefault(int(row), []).append(entry)
    return grouped


def matrix_rows(ledger, source=f"`{LEDGER}`"):
    """One line per defect row: the strongest evidence and the nets that fired, fired differently or stayed quiet."""
    defects = ledger.get("defects") or {}
    grouped = _by_row(ledger)
    lines = ["| Row | Defect | Known-bad → fix | Strongest evidence | Proven by | Fired differently "
             "| Stayed quiet (families) |", "| --- | --- | --- | --- | --- | --- | --- |"]
    for row in sorted({int(key) for key in defects} | set(grouped)):
        defect = defects.get(str(row)) or {}
        entries = sorted(grouped.get(row, []), key=lambda entry: str(entry.get("id")))
        proven = [entry for entry in entries if _state(entry) == "proven"]
        strongest = next((label for level, label in EVIDENCE
                          if any(entry.get("level") == level for entry in proven)), "none")
        if strongest == "none" and any(_state(entry) == "fired-differently" for entry in entries):
            strongest = "fired differently only"
        if any((entry.get("results") or {}).get("caveat") for entry in proven):
            strongest += " (caveat)"
        commits = (f"`{str((defect.get('knownBad') or {}).get('commit', '?'))[:8]}` → "
                   f"`{str((defect.get('fix') or {}).get('commit', '?'))[:8]}`")
        quiet = sorted({_family(entry) for entry in entries if _state(entry) not in ("proven", "fired-differently")})
        proven_by = ", ".join(f"`{entry.get('id')}` ({_short(entry)})" for entry in proven) or "-"
        differently = ", ".join(f"`{entry.get('id')}`" for entry in entries
                                if _state(entry) == "fired-differently") or "-"
        lines.append(f"| {row} | {_cell(defect.get('defect'), 70)} | {commits} | **{strongest}** | {proven_by} "
                     f"| {differently} | {_cell(', '.join(quiet), 160) or '-'} |")
    lines.append("")
    lines.append("*Strongest evidence*: generic > model > reproduction > tuned among proven entries; *(caveat)*: a "
                 f"proving entry records a caveat (see its `results.caveat`). Rendered from {source}; {REFRESH}.")
    return lines


def _short(entry):
    return {"generic": "generic", "reproduction": "repro", "model": "model",
            "tuned-after-fix": "tuned"}.get(entry.get("level"), str(entry.get("level")))


def firing_rows(ledger, source=f"`{LEDGER}`"):
    """Per net family: which defect rows it proved, at which level; generic firings are counted apart."""
    families = {}
    for entry in _entries(ledger):
        family = families.setdefault(_family(entry), {key: set() for key in (
            "generic", "model", "reproduction", "tuned-after-fix", "differently", "quiet")})
        state, level = _state(entry), entry.get("level")
        target = (level if state == "proven" and level in family else
                  "differently" if state == "fired-differently" else "quiet")
        family[target].update(int(row) for row in entry.get("rows") or [])
    order = sorted(families, key=lambda name: (-len(families[name]["generic"]), -len(families[name]["differently"]),
                                               -len(families[name]["reproduction"]), name))
    lines = ["| Net family | Generic proven (rows) | Fired differently | Reproduction | Model | Tuned "
             "| Not fired (rows) |", "| --- | --- | --- | --- | --- | --- | --- |"]

    def cell(values):
        return f"{len(values)}: {', '.join(str(value) for value in sorted(values))}" if values else "0"

    for name in order:
        family = families[name]
        quiet = family["quiet"] - family["generic"] - family["differently"]
        lines.append(f"| {_cell(name, 60)} | {cell(family['generic'])} | {cell(family['differently'])} "
                     f"| {cell(family['reproduction'])} | {cell(family['model'])} "
                     f"| {cell(family['tuned-after-fix'])} | {cell(quiet)} |")
    lines.append("")
    lines.append("Rows are defect rows of the ledger, counted once per family and column. *Not fired* lists rows "
                 "where an entry of the family stayed quiet and none of its entries proved the row generically or "
                 "fired differently (a row can also appear under reproduction or tuned). "
                 f"Rendered from {source}; {REFRESH}.")
    return lines


def entry_rows(ledger, source=f"`{LEDGER}`"):
    """Every entry: row, net, level, independence, class, result, time to yell, reproduction, proof id."""
    entries = sorted(_entries(ledger), key=lambda entry: (min(entry.get("rows") or [999]), str(entry.get("id"))))
    lines = ["| Row | Net | Level | Ind. | Class | Result | Time to yell | Reproduced | Proof |",
             "| --- | --- | --- | --- | --- | --- | --- | --- | --- |"]
    for entry in entries:
        net = entry.get("net") or {}
        known = (entry.get("results") or {}).get("knownBad") or {}
        seconds = known.get("timeToYellSeconds")
        tty = "-" if seconds is None else f"{seconds:g} s"
        lines.append(f"| {_rows_text(entry)} | {_cell(net.get('name'), 50)} | {_short(entry)} "
                     f"| {independence(entry.get('independence'))} | {net.get('evidenceClass', '?')} "
                     f"| **{_state(entry)}** | {tty} | {_cell(known.get('reproduced'), 70) or '-'} "
                     f"| `{entry.get('id')}` |")
    lines.append("")
    lines.append(f"{len(entries)} entries. Rendered from {source}; {REFRESH}.")
    return lines


BLOCKS = {"proven-obligations": rows, "verification-matrix": matrix_rows, "net-firings": firing_rows,
          "net-entries": entry_rows}


def render(ledger, source=f"`{LEDGER}`", name="proven-obligations"):
    return "\n".join([begin(name)] + BLOCKS[name](ledger, source) + [end(name)])


def refresh(text, ledger, source):
    """(updated text, names of the blocks found)."""
    found = []
    for name in BLOCKS:
        pattern = re.compile(re.escape(begin(name)) + r".*?" + re.escape(end(name)), re.S)
        if pattern.search(text):
            found.append(name)
            block = render(ledger, source, name)
            text = pattern.sub(lambda _: block, text, count=1)
    return text, found


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--ledger", help=f"Ledger file (default: {LEDGER} in the working tree)")
    parser.add_argument("--source", help="How the footer names the ledger (default: its path)")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--write", help="Replace the generated blocks in this file")
    group.add_argument("--check", help="Fail when a generated block in this file is stale")
    args = parser.parse_args(argv)
    path = Path(args.ledger) if args.ledger else Path(common.repo_root()) / LEDGER
    ledger = common.load_json_file(path)
    source = args.source or f"`{args.ledger or LEDGER}`"
    target = args.write or args.check
    if not target:
        print(render(ledger, source))
        return 0
    text = Path(target).read_text(encoding="utf-8")
    updated, found = refresh(text, ledger, source)
    if not found:
        print(f"ERROR: {target} has no '{BEGIN}' ... '{END}' block (nor another generated block)")
        return 1
    if args.check:
        if updated != text:
            print(f"ERROR: a generated table in {target} is stale; run render_net_proofs.py --write {target}")
            return 1
        print(f"{target}: generated tables are current ({', '.join(found)})")
        return 0
    Path(target).write_text(updated, encoding="utf-8")
    print(f"Wrote {', '.join(found)} to {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
