using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace LiteDB.SourceGenerator;

public sealed partial class BsonSourceGenerator
{
    private static string GenerateSource(IReadOnlyList<ModelDescriptor> models)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("namespace LiteDB.Generated");
        source.AppendLine("{");
        source.AppendLine("    public static class LiteDbGeneratedMappings");
        source.AppendLine("    {");
        source.AppendLine("        public static void Register(global::LiteDB.BsonMapper mapper)");
        source.AppendLine("        {");
        source.AppendLine("            if (mapper is null) throw new global::System.ArgumentNullException(nameof(mapper));");

        for (var index = 0; index < models.Count; index++)
        {
            source.Append("            var map").Append(index).Append(" = Create").Append(index).AppendLine("();");
        }

        source.AppendLine();
        for (var index = 0; index < models.Count; index++)
        {
            source.Append("            mapper.RegisterGeneratedEntityMapper(map").Append(index).AppendLine(");");
        }

        for (var index = 0; index < models.Count; index++)
        {
            if (models[index].CanEmitExecutionMap)
            {
                source.Append("            mapper.RegisterGeneratedExecutionMap(CreateExecutionMap").Append(index).AppendLine("());");
            }
        }

        source.AppendLine("        }");
        AppendStringListHelpers(source);
        if (HasStringArrayProperties(models))
        {
            AppendStringArrayHelpers(source);
        }

        if (HasDynamicDictionaryProperties(models))
        {
            AppendDynamicDictionaryHelpers(source);
        }

        if (HasDateTimeOffsetProperties(models))
        {
            AppendDateTimeOffsetHelpers(source);
        }

        for (var index = 0; index < models.Count; index++)
        {
            AppendFactory(source, models[index], index);
            if (models[index].CanEmitExecutionMap)
            {
                AppendExecutionMapFactory(source, models[index], index);
            }
        }

        source.AppendLine("    }");
        source.AppendLine("}");
        return source.ToString();
    }

    private static void AppendDateTimeOffsetHelpers(StringBuilder source)
    {
        source.AppendLine();
        source.AppendLine("        private static global::LiteDB.BsonValue SerializeDateTimeOffset(object? value)");
        source.AppendLine("        {");
        source.AppendLine("            if (value is null) return global::LiteDB.BsonValue.Null;");
        source.AppendLine("            var dateTimeOffset = (global::System.DateTimeOffset)value;");
        source.AppendLine("            return new global::LiteDB.BsonValue(dateTimeOffset.UtcDateTime);");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        private static object DeserializeDateTimeOffset(global::LiteDB.BsonValue value)");
        source.AppendLine("        {");
        source.AppendLine("            if (value.IsNull) return null!;");
        source.AppendLine("            if (value.IsDateTime)");
        source.AppendLine("            {");
        source.AppendLine("                return new global::System.DateTimeOffset(value.AsDateTime.ToUniversalTime());");
        source.AppendLine("            }");
        source.AppendLine("            var document = value.AsDocument;");
        source.AppendLine("            return new global::System.DateTimeOffset(");
        source.AppendLine("                document[\"DateTime\"].AsInt64,");
        source.AppendLine("                new global::System.TimeSpan(document[\"Offset\"].AsInt64));");
        source.AppendLine("        }");
    }

    private static void AppendStringListHelpers(StringBuilder source)
    {
        source.AppendLine();
        source.AppendLine("        private static global::LiteDB.BsonValue SerializeStringList(global::System.Collections.Generic.List<string>? values)");
        source.AppendLine("        {");
        source.AppendLine("            if (values is null) return global::LiteDB.BsonValue.Null;");
        source.AppendLine("            var result = new global::LiteDB.BsonArray();");
        source.AppendLine("            foreach (var value in values)");
        source.AppendLine("            {");
        source.AppendLine("                result.Add(value);");
        source.AppendLine("            }");
        source.AppendLine("            return result;");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        private static global::System.Collections.Generic.List<string>? DeserializeStringList(global::LiteDB.BsonValue value)");
        source.AppendLine("        {");
        source.AppendLine("            if (value.IsNull) return null;");
        source.AppendLine("            var result = new global::System.Collections.Generic.List<string>();");
        source.AppendLine("            foreach (var item in value.AsArray)");
        source.AppendLine("            {");
        source.AppendLine("                result.Add(item.AsString);");
        source.AppendLine("            }");
        source.AppendLine("            return result;");
        source.AppendLine("        }");
    }

    private static void AppendStringArrayHelpers(StringBuilder source)
    {
        source.AppendLine();
        source.AppendLine("        private static global::LiteDB.BsonValue SerializeStringArray(string[]? values)");
        source.AppendLine("        {");
        source.AppendLine("            if (values is null) return global::LiteDB.BsonValue.Null;");
        source.AppendLine("            var result = new global::LiteDB.BsonArray();");
        source.AppendLine("            foreach (var value in values)");
        source.AppendLine("            {");
        source.AppendLine("                result.Add(value);");
        source.AppendLine("            }");
        source.AppendLine("            return result;");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        private static string[]? DeserializeStringArray(global::LiteDB.BsonValue value)");
        source.AppendLine("        {");
        source.AppendLine("            if (value.IsNull) return null;");
        source.AppendLine("            var array = value.AsArray;");
        source.AppendLine("            var result = new string[array.Count];");
        source.AppendLine("            for (var index = 0; index < array.Count; index++)");
        source.AppendLine("            {");
        source.AppendLine("                result[index] = array[index].AsString;");
        source.AppendLine("            }");
        source.AppendLine("            return result;");
        source.AppendLine("        }");
    }

    private static void AppendDynamicDictionaryHelpers(StringBuilder source)
    {
        source.AppendLine();
        source.AppendLine("        private static global::LiteDB.BsonValue SerializeDynamicDictionaryForMap(global::System.Collections.Generic.Dictionary<string, object?>? values)");
        source.AppendLine("        {");
        source.AppendLine("            return SerializeDynamicDictionaryCore(values, null, 1);");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        private static global::LiteDB.BsonValue SerializeDynamicDictionaryCore(global::System.Collections.Generic.Dictionary<string, object?>? values, global::LiteDB.GeneratedExecutionOptions? options, int depth)");
        source.AppendLine("        {");
        source.AppendLine("            if (values is null) return global::LiteDB.BsonValue.Null;");
        source.AppendLine("            var result = new global::LiteDB.BsonDocument();");
        source.AppendLine("            foreach (var pair in values)");
        source.AppendLine("            {");
        source.AppendLine("                result[pair.Key] = SerializeDynamicValue(pair.Value, options, depth + 1);");
        source.AppendLine("            }");
        source.AppendLine("            return result;");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        private static global::LiteDB.BsonValue SerializeDynamicValue(object? value, global::LiteDB.GeneratedExecutionOptions? options, int depth)");
        source.AppendLine("        {");
        source.AppendLine("            if (depth > 20) throw new global::System.InvalidOperationException(\"The dynamic dictionary exceeds the supported maximum depth of 20.\");");
        source.AppendLine("            if (value is null) return global::LiteDB.BsonValue.Null;");
        source.AppendLine("            return value switch");
        source.AppendLine("            {");
        source.AppendLine("                global::LiteDB.BsonValue bsonValue => bsonValue,");
        source.AppendLine("                int integer => new global::LiteDB.BsonValue(integer),");
        source.AppendLine("                long integer => new global::LiteDB.BsonValue(integer),");
        source.AppendLine("                double number => new global::LiteDB.BsonValue(number),");
        source.AppendLine("                decimal number => new global::LiteDB.BsonValue(number),");
        source.AppendLine("                string text => SerializeDynamicString(text, options),");
        source.AppendLine("                byte[] bytes => new global::LiteDB.BsonValue(bytes),");
        source.AppendLine("                global::LiteDB.ObjectId objectId => new global::LiteDB.BsonValue(objectId),");
        source.AppendLine("                global::System.Guid guid => new global::LiteDB.BsonValue(guid),");
        source.AppendLine("                bool boolean => new global::LiteDB.BsonValue(boolean),");
        source.AppendLine("                global::System.DateTime dateTime => new global::LiteDB.BsonValue(dateTime),");
        source.AppendLine("                short integer => new global::LiteDB.BsonValue((int)integer),");
        source.AppendLine("                ushort integer => new global::LiteDB.BsonValue((int)integer),");
        source.AppendLine("                byte integer => new global::LiteDB.BsonValue((int)integer),");
        source.AppendLine("                sbyte integer => new global::LiteDB.BsonValue((int)integer),");
        source.AppendLine("                uint integer => new global::LiteDB.BsonValue((long)integer),");
        source.AppendLine("                ulong integer => new global::LiteDB.BsonValue(unchecked((long)integer)),");
        source.AppendLine("                float number => new global::LiteDB.BsonValue((double)number),");
        source.AppendLine("                char character => new global::LiteDB.BsonValue(character.ToString()),");
        source.AppendLine("                global::System.Enum enumeration => options?.EnumAsInteger == true ? new global::LiteDB.BsonValue(global::System.Convert.ToInt32(enumeration)) : new global::LiteDB.BsonValue(enumeration.ToString()),");
        source.AppendLine("                global::System.Collections.Generic.Dictionary<string, object?> dictionary => SerializeDynamicDictionaryCore(dictionary, options, depth),");
        source.AppendLine("                global::System.Collections.IDictionary => throw new global::System.InvalidOperationException($\"Unsupported dynamic dictionary value type '{value.GetType().FullName}'. Nested dictionaries must be Dictionary<string, object?>.\"),");
        source.AppendLine("                global::System.Collections.IEnumerable values => SerializeDynamicArray(values, options, depth),");
        source.AppendLine("                _ => throw new global::System.InvalidOperationException($\"Unsupported dynamic dictionary value type '{value.GetType().FullName}'. Use BSON-native values, nested dictionaries, or nested enumerables.\")");
        source.AppendLine("            };");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        private static global::LiteDB.BsonValue SerializeDynamicString(string value, global::LiteDB.GeneratedExecutionOptions? options)");
        source.AppendLine("        {");
        source.AppendLine("            var text = options?.TrimWhitespace != false ? value.Trim() : value;");
        source.AppendLine("            return options?.EmptyStringToNull != false && text.Length == 0 ? global::LiteDB.BsonValue.Null : new global::LiteDB.BsonValue(text);");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        private static global::LiteDB.BsonValue SerializeDynamicArray(global::System.Collections.IEnumerable values, global::LiteDB.GeneratedExecutionOptions? options, int depth)");
        source.AppendLine("        {");
        source.AppendLine("            var result = new global::LiteDB.BsonArray();");
        source.AppendLine("            foreach (var value in values)");
        source.AppendLine("            {");
        source.AppendLine("                result.Add(SerializeDynamicValue(value, options, depth + 1));");
        source.AppendLine("            }");
        source.AppendLine("            return result;");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        private static global::System.Collections.Generic.Dictionary<string, object?>? DeserializeDynamicDictionary(global::LiteDB.BsonValue value)");
        source.AppendLine("        {");
        source.AppendLine("            return value.IsNull ? null : DeserializeDynamicDocument(value.AsDocument);");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        private static global::System.Collections.Generic.Dictionary<string, object?> DeserializeDynamicDocument(global::LiteDB.BsonDocument values)");
        source.AppendLine("        {");
        source.AppendLine("            var result = new global::System.Collections.Generic.Dictionary<string, object?>();");
        source.AppendLine("            foreach (var pair in values.GetElements())");
        source.AppendLine("            {");
        source.AppendLine("                result[pair.Key] = DeserializeDynamicValue(pair.Value);");
        source.AppendLine("            }");
        source.AppendLine("            return result;");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        private static object?[] DeserializeDynamicArray(global::LiteDB.BsonArray values)");
        source.AppendLine("        {");
        source.AppendLine("            var result = new object?[values.Count];");
        source.AppendLine("            for (var index = 0; index < values.Count; index++)");
        source.AppendLine("            {");
        source.AppendLine("                result[index] = DeserializeDynamicValue(values[index]);");
        source.AppendLine("            }");
        source.AppendLine("            return result;");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        private static object? DeserializeDynamicValue(global::LiteDB.BsonValue value)");
        source.AppendLine("        {");
        source.AppendLine("            if (value.IsNull) return null;");
        source.AppendLine("            return value.Type switch");
        source.AppendLine("            {");
        source.AppendLine("                global::LiteDB.BsonType.Document => DeserializeDynamicDocument(value.AsDocument),");
        source.AppendLine("                global::LiteDB.BsonType.Array => DeserializeDynamicArray(value.AsArray),");
        source.AppendLine("                _ => value.RawValue");
        source.AppendLine("            };");
        source.AppendLine("        }");
    }

    private static bool HasDynamicDictionaryProperties(IReadOnlyList<ModelDescriptor> models)
    {
        return models.Any(static model => model.Properties.Any(static property => property.Kind == PropertyKind.DynamicDictionary));
    }

    private static bool HasStringArrayProperties(IReadOnlyList<ModelDescriptor> models)
    {
        return models.Any(static model => model.Properties.Any(static property => property.Kind == PropertyKind.StringArray));
    }

    private static bool HasDateTimeOffsetProperties(IReadOnlyList<ModelDescriptor> models)
    {
        return models.Any(static model => model.Properties.Any(static property =>
            property.Kind is PropertyKind.DateTimeOffset or PropertyKind.NullableDateTimeOffset));
    }

    private static void AppendFactory(StringBuilder source, ModelDescriptor model, int index)
    {
        source.AppendLine();
        source.Append("        private static global::LiteDB.EntityMapper Create").Append(index).AppendLine("()");
        source.AppendLine("        {");
        source.Append("            var map = new global::LiteDB.EntityMapper(typeof(").Append(model.TypeName).AppendLine("))");
        source.AppendLine("            {");
        source.Append("                CreateInstance = _ => new ").Append(model.TypeName).AppendLine("()");
        source.AppendLine("            };");

        foreach (var property in model.Properties)
        {
            source.AppendLine();
            source.AppendLine("            map.Members.Add(new global::LiteDB.MemberMapper");
            source.AppendLine("            {");
            source.Append("                AutoId = ").Append(property.IsId && property.AutoId ? "true" : "false").AppendLine(",");
            source.Append("                FieldName = ").Append(SymbolDisplay.FormatLiteral(property.FieldName, true)).AppendLine(",");
            source.Append("                MemberName = ").Append(SymbolDisplay.FormatLiteral(property.Name, true)).AppendLine(",");
            source.Append("                DataType = typeof(").Append(property.TypeName).AppendLine("),");
            source.Append("                UnderlyingType = typeof(").Append(property.Kind is PropertyKind.StringList or PropertyKind.StringArray ? "global::System.String" : property.TypeName).AppendLine("),");
            source.Append("                IsEnumerable = ").Append(property.Kind is PropertyKind.StringList or PropertyKind.StringArray ? "true" : "false").AppendLine(",");

            if (property.Kind == PropertyKind.StringList)
            {
                source.AppendLine("                Serialize = (value, _) => SerializeStringList((global::System.Collections.Generic.List<string>)value),");
                source.Append("                Deserialize = (value, _) => DeserializeStringList(value)").AppendLine(",");
            }
            else if (property.Kind == PropertyKind.StringArray)
            {
                source.AppendLine("                Serialize = (value, _) => SerializeStringArray((string[])value),");
                source.Append("                Deserialize = (value, _) => DeserializeStringArray(value)").AppendLine(",");
            }
            else if (property.Kind == PropertyKind.DynamicDictionary)
            {
                source.AppendLine("                Serialize = (value, _) => SerializeDynamicDictionaryForMap((global::System.Collections.Generic.Dictionary<string, object?>)value),");
                source.Append("                Deserialize = (value, _) => DeserializeDynamicDictionary(value)").AppendLine(",");
            }
            else if (property.Kind is PropertyKind.DateTimeOffset or PropertyKind.NullableDateTimeOffset)
            {
                source.AppendLine("                Serialize = (value, _) => SerializeDateTimeOffset(value),");
                source.Append("                Deserialize = (value, _) => DeserializeDateTimeOffset(value)").AppendLine(",");
            }

            source.Append("                Getter = entity => ((").Append(model.TypeName).Append(")entity).").Append(property.Identifier).AppendLine(",");
            source.Append("                Setter = (entity, value) => ((").Append(model.TypeName).Append(")entity).").Append(property.Identifier).Append(" = (").Append(property.Kind == PropertyKind.DynamicDictionary ? "global::System.Collections.Generic.Dictionary<string, object?>" : property.TypeName).AppendLine(")value");
            source.AppendLine("            });");
        }

        source.AppendLine();
        source.AppendLine("            return map;");
        source.AppendLine("        }");
    }

}
