<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup Condition="'$(LiteDBAssembly)' == ''">
    <ProjectReference Include="../../LiteDB/LiteDB.csproj" AdditionalProperties="TestingEnabled=false" />
  </ItemGroup>
  <ItemGroup Condition="'$(LiteDBAssembly)' != ''">
    <Reference Include="LiteDB" HintPath="$(LiteDBAssembly)" />
  </ItemGroup>
</Project>
