<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net481</TargetFramework>
    <PlatformTarget Condition="'$(PlatformTarget)' == ''">AnyCPU</PlatformTarget>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>LiteDB.Fuzz.Legacy</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LiteDB\LiteDB.csproj"
                      SetTargetFramework="TargetFramework=netstandard2.0"
                      AdditionalProperties="TestingEnabled=true" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
