<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Program.cs" />
    <Compile Include="../Measurements.cs" />
    <ProjectReference Include="../../../LiteDB/LiteDB.csproj" />
  </ItemGroup>
</Project>
