name: Publish prerelease

on:
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Set prerelease version
        id: version
        run: |
          # Use SemVer-compliant prerelease without leading zeros
          echo "package_version=6.0.0-prerelease.${{ github.run_number }}" >> "$GITHUB_OUTPUT"
          echo "Version set to 6.0.0-prerelease.${{ github.run_number }}"

      - name: Restore
        run: dotnet restore LiteDB.sln

      - name: Test (with hang diagnostics)
        timeout-minutes: 8
        env:
          VSTEST_TESTHOST_HANG_DUMP_TYPE: full
          VSTEST_TESTHOST_HANG_DUMP_FOLDER: ${{ github.workspace }}/hangdumps
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          DOTNET_NOLOGO: 1
        run: >-
          dotnet test LiteDB.sln
          --configuration Release
          --verbosity normal
          --settings tests.ci.runsettings
          --logger "trx;LogFileName=TestResults.trx"
          --logger "console;verbosity=detailed"
          --blame-hang --blame-hang-timeout 00:02:00
          --diag "TestHost.diag.log;tracelevel=verbose"
          /p:DefineConstants=TESTING

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: "**/*TestResults*.trx"
      
      - name: Upload hang dumps (if any)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: hangdumps
          path: |
            hangdumps
            **/TestResults/**/*.dmp
          if-no-files-found: ignore

      - name: Build
        if: success()
        run: dotnet build LiteDB/LiteDB.csproj --configuration Release --no-restore -p:Version=${{ steps.version.outputs.package_version }} -p:PackageVersion=${{ steps.version.outputs.package_version }} -p:MinVerSkip=true

      - name: Pack
        if: success()
        run: dotnet pack LiteDB/LiteDB.csproj --configuration Release --no-build -o artifacts -p:PackageVersion=${{ steps.version.outputs.package_version }} -p:Version=${{ steps.version.outputs.package_version }} -p:MinVerSkip=true

      - name: Publish GitHub prerelease
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.package_version }}
          name: LiteDB ${{ steps.version.outputs.package_version }}
          generate_release_notes: true
          prerelease: true
          files: artifacts/*.nupkg
          target_commitish: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Retrieve secrets from Bitwarden
        if: success()
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          base_url: https://vault.bitwarden.eu
          secrets: |
            265b2fb6-2cf0-4859-9bc8-b24c00ab4378 > NUGET_API_KEY

      - name: Push package to NuGet
        if: success()
        run: |
          dotnet nuget push "artifacts/*.nupkg" --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json --skip-duplicate

